#!/bin/bash

if [[ "${#*}" -lt 3 ]]
then
	echo "--------------------------------------------------------------------------"
	echo "Uso: PTrack2BashFolders [Prefijo] [nInicial] [nFinal]"
	echo "Ejemplo: ptrackingBashFolders Acquis"
	echo "-Prefijo: Prefijo de las carpetas a ser procesadas, las carpetas deben terminar con 3 dijitos ej: Acquis###"
	echo "-nInicial: Numero inicial de las carpeta a procesar"
	echo "-nFinal: Numero final de las carpetas a procesar"
	echo "--------------------------------------------------------------------------"
	exit
fi

SUB_FOLDER=$1
INIT_NUM=$2
FINAL_NUM=$3

configfile=./PTrack2BashFolders.conf
if [ -r $configfile ]
then
	echo ">> Reading user configuration file..."
	if egrep -q -z -v '^#|^[^ ]*=[^;]*|$([*])' $configfile
	then
		echo ">> Configuration file is unclean, please cleaning it..."
		exit
	fi
	source $configfile
	echo ">> Configuration file OK"

	echo ">> Image Folder: $IMG_FOLDER"
	echo ">> Destination Folder: $DEST"
	for (( i=$INIT_NUM; i<$FINAL_NUM; ++i ))
	do
		echo ">> Data for $i: D=${Data_D[$i]}, W=${Data_W[$i]};"
	done
else
	echo ">> No configuration file found, please create a new one."
	exit
fi

FIX=3
function main {
	for (( i=$INIT_NUM; i<=$FINAL_NUM; ++i ))
	do
		num="000"$i
		folder=$SUB_FOLDER${num:${#num}-3:3}
		echo ">> Processing $folder/$IMG_FOLDER -> $folder/$DEST -> ${Data_D[$i]} -> ${Data_W[$i]}"
		PTrack2Bash $folder/$IMG_FOLDER $folder/$DEST ${Data_D[$i]} ${Data_W[$i]}
		echo ">> Processing $folder/$IMG_FOLDER complete"
	done
}

time main